# Generated by Django 4.2.4 on 2024-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('car_model', models.TextField()),
                ('car_category', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
